Minor meta updates
the-eater/shinit pull request #2
Opened 2017-08-06 15:09 UTC by Tyil

This PR just applies some minor updates, mostly to metafiles.

The most important aspect however is the `license` field in the `META6.json`. As of right now there is no license available at all, which makes it non-free software. I've set it as `GPL-3.0` in the `META6.json` as this is my preferred license, but any free license should work.

2017-08-06 16:13 UTC, the-eater commented
:+1: -comments

2017-08-06 16:13 UTC, the-eater requested changes

2017-08-06 16:13 UTC, the-eater commented on META6.json
> +    "source-url": "https://github.com/the-eater/shinit"
missing `.git`

2017-08-06 16:13 UTC, the-eater commented on META6.json
> +    "auth": "the-eater:shinit",
Wasn't it `github:the-eater`?

2017-08-07 10:40 UTC, Tyil commented
Updated the `META6.json` as per your request.

2017-08-07 13:33 UTC, merged

2017-08-07 13:33 UTC, the-eater commented
Thanks :)